# Generated by Django 5.1.1 on 2024-11-16 16:57

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('content', django_quill.fields.QuillField()),
                ('short_content', django_quill.fields.QuillField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='static/assets/img/hero-bg.jpg', null=True, upload_to='static/%Y/%m/%d/blogimages')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('feature', models.BooleanField(default=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(default='Kyaw Soe Hla', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'ordering': ('-created',),
            },
        ),
    ]
