# Generated by Django 5.1.1 on 2024-11-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='short_content',
        ),
    ]
